"""
Example of usage of the vaby framework to infer a single exponential decay
model.
"""
import argparse
import sys

import numpy as np
import tensorflow as tf

import vaby

cli = argparse.ArgumentParser()
cli.add_argument("--method", help="Inference method", choices=["avb", "svb"], default="avb")
cli.add_argument("--amp", help="Ground truth amplitude", type=float, default=42.0)
cli.add_argument("--rate", help="Ground truth decay rate", type=float, default=0.5)
cli.add_argument("--dt", help="Time resolution", type=float, default=0.1)
cli.add_argument("--nt", help="Number of time points", type=int, default=100)
cli.add_argument("--noise", help="Ground truth noise amplitude (std dev)", type=float, default=5)
cli.add_argument("--rseed", help="Random number seed to give reproducible results", type=int)
cli.add_argument("--debug", help="Debug logging", action="store_true", default=False)
cli.add_argument("--fabber", help="Run Fabber as a comparison", action="store_true", default=False)
cli.add_argument("--plot", help="Show output graphically", action="store_true", default=False)
opts = cli.parse_args()

if opts.rseed:
    np.random.seed(opts.rseed)
    tf.random.set_seed(opts.rseed)

# Ground truth parameters
PARAMS_TRUTH = [opts.amp, opts.rate]
NOISE_STD_TRUTH = opts.noise
NOISE_VAR_TRUTH = NOISE_STD_TRUTH**2
NOISE_PREC_TRUTH = 1/NOISE_VAR_TRUTH
print("Ground truth: a=%f, r=%f, noise=%f (std.dev.)" % (PARAMS_TRUTH[0], PARAMS_TRUTH[1], NOISE_STD_TRUTH))

# Observed data samples are generated by Numpy from the ground truth
# Gaussian distribution. Reducing the number of samples should make
# the inference less 'confident' - i.e. the output variances for
# MU and BETA will increase
temp_model = vaby.get_model_class("exp")(None, dt=opts.dt)
t = np.array([float(t)*opts.dt for t in range(opts.nt)])
DATA_CLEAN = temp_model.evaluate(PARAMS_TRUTH, t).numpy()
DATA_NOISY = DATA_CLEAN + np.random.normal(0, NOISE_STD_TRUTH, [opts.nt])

if opts.fabber:
    import os
    import nibabel as nib
    niidata = DATA_NOISY.reshape((1, 1, 1, opts.nt))
    nii = nib.Nifti1Image(niidata, np.identity(4))
    nii.to_filename("data_noisy.nii.gz")
    os.system("fabber_exp --data=data_noisy --print-free-energy --save-model-fit --output=exp_example_fabber_out --dt=%.3f --model=exp --num-exps=1 --method=vb --max-iterations=50 --noise=white --overwrite --debug" % opts.dt)
    fabber_modelfit = nib.load("exp_example_fabber_out/modelfit.nii.gz").get_fdata().reshape([opts.nt])

# Run inference
data_model = vaby.DataModel(DATA_NOISY)
fwd_model = vaby.get_model_class("exp")(data_model, dt=opts.dt)

inference_options = {
    "method" : opts.method,
    "dt" : opts.dt,
    "debug" : opts.debug,
    "log_stream" : sys.stdout,
}
if opts.method == "svb":
    inference_options.update({
        "epochs" : 300,
        "learning_rate" : 0.1,
        "sample_size" : 10,
    })
else:
    inference_options.update({
        "max_iterations" : 20,
    })

runtime, state = vaby.run(DATA_NOISY, "exp", **inference_options)

if opts.plot:
    from matplotlib import pyplot as plt
    plt.figure(1)
    plt.title("Example inference of single exponential")
    plt.plot(t, DATA_CLEAN, "b-", label="Ground truth")
    plt.plot(t, DATA_NOISY, "kx", label="Noisy samples", )
    plt.plot(t, state["modelfit"][0], "g--", label="Model fit")
    if opts.fabber:
        plt.plot(t, fabber_modelfit, "r--", label="Fabber model fit")
    plt.legend()
    plt.show()
